apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fabiosol/annotationsapp:backend
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://backend:password@mongodb:27017/data

