apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8.0.0-rc20
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGODB_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongodb-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongodb-init-scripts
          configMap:
            name: mongodb-init-scripts